--- arch/mips64/kernel/Makefile	2003-08-25 11:44:40.000000000 +0000
+++ arch/mips64/kernel/Makefile	2004-01-06 12:43:53.000000000 +0000
@@ -12,7 +12,7 @@
 
 O_TARGET := kernel.o
 
-export-objs	= irq.o mips64_ksyms.o pci-dma.o setup.o smp.o time.o
+export-objs	= irq.o mips64_ksyms.o pci-dma.o setup.o semaphore.o smp.o time.o
 
 obj-y		:= branch.o cpu-probe.o entry.o irq.o proc.o process.o \
 		   ptrace.o r4k_cache.o r4k_fpu.o r4k_genex.o r4k_switch.o \
