--- arch/cris/drivers/Makefile	2003-06-13 14:51:29.000000000 +0000
+++ arch/cris/drivers/Makefile	2004-01-06 12:41:57.000000000 +0000
@@ -4,6 +4,8 @@
 
 O_TARGET := drivers.o
 
+export-objs := axisflashmap.o
+
 obj-y :=
 
 obj-$(CONFIG_ETRAX_VIRTEX_FPGA)         += virtex.o
