--- arch/mips/lasat/Makefile	2003-08-25 11:44:40.000000000 +0000
+++ arch/mips/lasat/Makefile	2004-01-06 12:43:42.000000000 +0000
@@ -5,7 +5,7 @@
 
 O_TARGET := lasatkern.o
 obj-y	 := reset.o setup.o prom.o lasat_board.o \
-		crc32.o at93c.o interrupt.o lasatIRQ.o
+		at93c.o interrupt.o lasatIRQ.o
 
 obj-$(CONFIG_LASAT_SYSCTL) += sysctl.o
 
