--- arch/ppc/boot/simple/Makefile	2003-11-28 18:26:19.000000000 +0000
+++ arch/ppc/boot/simple/Makefile	2004-01-06 12:42:08.000000000 +0000
@@ -9,12 +9,10 @@
 # or implied.
 #
 # Notes:
-# (1) For machine targets which produce more than one image, define
-# ZNETBOOT and ZNETBOOTRD to the image which should be available for
-# 'znetboot' and 'znetboot.initrd`
-# (2) For machine targets which use the mktree program, define END to be
-# the machine name you want in the image, and you can optionally set
-# ENTRYPOINT which the image should be loaded at.  The optimal setting
+# (1) All machines must set the END variable to the suffix of the preferred
+# final image (i.e. would be copied in 'make znetboot'.
+# (2) For machine targets which use the mktree program you can optionally
+# set ENTRYPOINT which the image should be loaded at.  The optimal setting
 # for ENTRYPOINT is the link address.
 
 USE_STANDARD_AS_RULE		:= true
@@ -25,15 +23,13 @@
 ifeq ($(CONFIG_EMBEDDEDBOOT),y)
 ZIMAGE				:= zImage-EMBEDDED
 ZIMAGEINITRD			:= zImage.initrd-EMBEDDED
-TFTPIMAGE			:= /tftpboot/zImage.embedded
 MISC				:= misc-embedded.o
+END				:= embedded
 endif
 ifeq ($(CONFIG_IBM_OPENBIOS),y)
 ZIMAGE				:= zImage-TREE
 ZIMAGEINITRD			:= zImage.initrd-TREE
 END				:= treeboot
-ZNETBOOT			:= zImage.treeboot
-ZNETBOOTRD			:= zImage.initrd.treeboot
 TFTPIMAGE			:= /tftpboot/zImage.embedded
 MISC				:= misc-embedded.o
 endif
@@ -42,9 +38,6 @@
 ZIMAGEINITRD			:= zImage.initrd-TREE
 END				:= ebony
 ENTRYPOINT			:= 0x00800000
-ZNETBOOT			:= zImage.treeboot
-ZNETBOOTRD			:= zImage.initrd.treeboot
-TFTPIMAGE			:= /tftpboot/zImage.$(END)
 EXTRA				:= misc-44x.o
 endif
 ifeq ($(CONFIG_OCOTEA),y)
@@ -52,25 +45,21 @@
 ZIMAGEINITRD			:= zImage.initrd-TREE
 END				:= ocotea
 ENTRYPOINT			:= 0x00800000
-ZNETBOOT			:= zImage.treeboot
-ZNETBOOTRD			:= zImage.initrd.treeboot
-TFTPIMAGE			:= /tftpboot/zImage.$(END)
 EXTRA				:= misc-44x.o
 endif
 ifeq ($(CONFIG_GEMINI),y)
 ZIMAGE				:= zImage-SMON
 ZIMAGEINITRD			:= zImage.initrd-SMON
-TFTPIMAGE			:= /tftpboot/zImage.gemini
+END				:= gemini
 endif
 # kbuild-2.4 'feature', only one of these will ever by 'y' at a time.
 # The rest will be unset.
-ifeq ($(CONFIG_LOPEC)$(CONFIG_PPLUS),y)
+ifeq ($(CONFIG_LOPEC)$(CONFIG_PPLUS)$(CONFIG_PRPMC750),y)
 ZIMAGE				:= zImage-PPLUS
 ZIMAGEINITRD			:= zImage.initrd-PPLUS
 EXTRA				:= ../common/mpc10x_memory.o
 TFTPIMAGE			:= /tftpboot/zImage.pplus
-ZNETBOOT			:= zImage.pplus
-ZNETBOOTRD			:= zImage.initrd.pplus
+END				:= pplus
 endif
 ifeq ($(CONFIG_PPLUS),y)
 EXTRA				:= legacy.o
@@ -78,7 +67,14 @@
 ifeq ($(CONFIG_PAL4),y)
 ZIMAGE				:= zImage-PAL4
 ZIMAGEINITRD			:= zImage.initrd-PAL4
-TFTPIMAGE			:= /tftpboot/zImage.pal4
+END				:= pal4
+endif
+ifeq ($(CONFIG_SANDPOINT),y)
+ZIMAGE				:= zImage-SP
+ZIMAGEINITRD			:= zImage.initrd-SP
+CACHEFLAG			:= -include clear.S
+TFTPIMAGE			:= /tftpboot/zImage.sandpoint
+END				:= sandpoint
 endif
 ifeq ($(CONFIG_SPRUCE),y)
 ZIMAGE				:= zImage-TREE
@@ -86,12 +82,14 @@
 ENTRYPOINT			:= 0x00800000
 MISC				:= misc-spruce.o
 END				:= spruce
-TFTPIMAGE			:= /tftpboot/zImage.$(END)
 endif
+
+TFTPIMAGE			?= /tftpboot/zImage.$(END)
 ifeq ($(CONFIG_SMP),y)
 TFTPIMAGE			+= .smp
 endif
 
+
 # Setup a default address to put ourselves, change it as needed.
 LD_ARGS				= -T ../ld.script -Ttext 0x00800000 -Bstatic
 ifdef CONFIG_8xx
@@ -156,30 +154,22 @@
 	rm -f zvmlinux.initrd
 
 znetboot: zImage
-ifneq ($(ZNETBOOT),)
-	cp ../images/$(ZNETBOOT) $(TFTPIMAGE)
-else
-	cp ../images/zImage.* $(TFTPIMAGE)
-endif
+	cp ../images/zImage.$(END) $(TFTPIMAGE)
 
 znetboot.initrd: zImage.initrd
-ifneq ($(ZNETBOOTRD),)
-	cp ../images/$(ZNETBOOTRD) $(TFTPIMAGE)
-else
-	cp ../images/zImage.* $(TFTPIMAGE)
-endif
+	cp ../images/zImage.initrd.$(END) $(TFTPIMAGE)
 
 zImage-EMBEDDED: zvmlinux
-	mv zvmlinux ../images/zImage.embedded
+	mv zvmlinux ../images/zImage.$(END)
 
 zImage.initrd-EMBEDDED: zvmlinux.initrd
-	mv zvmlinux.initrd ../images/zImage.initrd.embedded
+	mv zvmlinux.initrd ../images/zImage.initrd.$(END)
 
 zImage-PAL4: zvmlinux
-	mv zvmlinux ../images/zImage.pal4
+	mv zvmlinux ../images/zImage.$(END)
 
 zImage.initrd-PAL4: zvmlinux.initrd
-	mv zvmlinux.initrd ../images/zImage.initrd.pal4
+	mv zvmlinux.initrd ../images/zImage.initrd.$(END)
 
 zImage-PPLUS: zvmlinux $(MKPREP) $(MKBUGBOOT)
 	$(MKPREP) -pbp zvmlinux ../images/zImage.pplus
@@ -189,11 +179,17 @@
 	$(MKPREP) -pbp zvmlinux.initrd ../images/zImage.initrd.pplus
 	$(MKBUGBOOT) zvmlinux.initrd ../images/zImage.initrd.bugboot
 
+zImage-SP: zvmlinux
+	mv zvmlinux ../images/zImage.sandpoint
+
+zImage.initrd-SP: zvmlinux.initrd
+	mv zvmlinux.initrd ../images/zImage.initrd.sandpoint
+
 zImage-SMON: zvmlinux
-	dd if=zvmlinux of=../images/zImage.gemini skip=64 bs=1k
+	dd if=zvmlinux of=../images/zImage.$(END) skip=64 bs=1k
 
 zImage.initrd-SMON: zvmlinux.initrd
-	dd if=zvmlinux.initrd of=../images/zImage.initrd.gemini skip=64 bs=1k
+	dd if=zvmlinux.initrd of=../images/zImage.initrd.$(END) skip=64 bs=1k
 
 zImage-TREE: zvmlinux
 	$(MKTREE) zvmlinux ../images/zImage.$(END) $(ENTRYPOINT)
