--- arch/mips64/lib/Makefile	2003-08-25 11:44:40.000000000 +0000
+++ arch/mips64/lib/Makefile	2004-01-06 12:45:57.000000000 +0000
@@ -10,7 +10,12 @@
 	  rtc-no.o memset.o memcpy.o strlen_user.o strncpy_user.o \
 	  strnlen_user.o watch.o
 
-obj-$(CONFIG_BLK_DEV_FD)	+= floppy-no.o floppy-std.o
+#
+# The ugly subst stuff is here only because I hesistate to stuff the IDE and
+# floppy bits into the kernel of every machine that possibly might load a
+# module ...
+#
+obj-$(subst m,y,$(CONFIG_BLK_DEV_FD))	+= floppy-no.o floppy-std.o
 obj-$(subst m,y,$(CONFIG_IDE))	+= ide-std.o ide-no.o	# needed for ide module
 obj-$(CONFIG_PC_KEYB)		+= kbd-std.o
 
